# Generated by Django 4.2.2 on 2023-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Iris",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("SpeL", models.FloatField()),
                ("SpeW", models.FloatField()),
                ("PetL", models.FloatField()),
                ("PetW", models.FloatField()),
                ("Species", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "iris",
            },
        ),
        migrations.CreateModel(
            name="OrderSum",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("orderNum", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ordersum",
            },
        ),
        migrations.CreateModel(
            name="PositionInfo",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("post", models.CharField(max_length=20, null=True)),
                ("level", models.CharField(max_length=20, null=True)),
            ],
            options={
                "db_table": "positioninfo",
            },
        ),
    ]
