# Generated by Django 4.2.2 on 2023-06-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files/")),
                ("filename", models.CharField(max_length=50, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "文件",
                "db_table": "file",
            },
        ),
        migrations.CreateModel(
            name="Iris",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("SpeL", models.FloatField()),
                ("SpeW", models.FloatField()),
                ("PetL", models.FloatField()),
                ("PetW", models.FloatField()),
                ("Species", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "iris",
            },
        ),
        migrations.CreateModel(
            name="OrderSum",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("orderNum", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ordersum",
            },
        ),
        migrations.CreateModel(
            name="PositionInfo",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("post", models.CharField(max_length=20, null=True)),
                ("level", models.CharField(max_length=20, null=True)),
            ],
            options={
                "db_table": "positioninfo",
            },
        ),
    ]
