# Generated by Django 4.2.2 on 2023-06-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aprioridb",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("item1", models.CharField(max_length=20, null=True)),
                ("item2", models.CharField(max_length=20, null=True)),
                ("item3", models.CharField(max_length=20, null=True)),
                ("item4", models.CharField(max_length=20, null=True)),
            ],
            options={
                "verbose_name": "关联规则",
                "db_table": "aprioridb",
            },
        ),
    ]
