# Generated by Django 4.2.2 on 2023-06-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_regressiondata"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlobsDataSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("label", models.IntegerField()),
            ],
            options={
                "verbose_name": "Blobs数据集",
                "db_table": "BlobsDataSet",
            },
        ),
        migrations.CreateModel(
            name="MoonsDataSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("label", models.IntegerField()),
            ],
            options={
                "verbose_name": "Moons数据集",
                "db_table": "MoonsDataSet",
            },
        ),
    ]
